name: carbo
description: carbo

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: 4.7.2
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  flutter_inappwebview: ^6.1.5
  get_storage: ^2.1.1
  flutter_svg: 2.0.17
  r_dotted_line_border: ^0.1.1
  carousel_slider: ^5.0.0
  cached_network_image:
  image_picker: 1.1.2
  logger: ^2.4.0
  lottie: any
  iconsax: ^0.0.8
  dropdown_button2: ^2.3.9
  restart_app: ^1.3.2
  dynamic_languages:
    git:
      url: https://github.com/appdevsx/dynamic_languages
      ref: main



  imageview360:
  loading_animation_widget: ^1.3.0


  flutter_animate: ^4.5.2
  pin_code_fields: ^8.0.1
  csv: ^6.0.0
  dart_code_metrics:

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name:
  flutter_launcher_icons:
  rename_app:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/icons/
    - assets/logo/
